# Generated by Django 4.0.4 on 2022-05-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='track',
            new_name='tracks',
        ),
        migrations.AlterField(
            model_name='track',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
